---
title: "MDM-RSN10"
author: "Simon Schwab"
date: "9 Jun 2017"
output: html_document
---

## Install R Markdown 
```{r Install R Markdown}
# install.packages("rmarkdown")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Install required packages 
```{r install required packages}
# install.packages("devtools")
# install.packages("testit")
# install.packages("ggplot2")
# install.packages("cowplot")
# install.packages("reshape2")
# install.packages("data.table")
# install.packages("testthat")
```

## Load libraries 
```{r Load required libraries, message=FALSE}
library(devtools)
library(testit)
library(ggplot2)
library(cowplot)
library(reshape2)
library(data.table)
library(testthat)
```

## Install and load multdyn 
```{r Install multdyn, message=FALSE}
# install_github("schw4b/multdyn", ref = "develop")
# library(multdyn)

# I'm using my local development branch
# strange I needed to install data.table, testthat maunally
load_all('~/workspace/multdyn')
```

## Main variables 
```{r Main variables}
PATH_HOME = "/home/simon"
PATH_NET  = file.path(PATH_HOME, 'Drive', 'MDM_NetMats10_results')
PATH_TS   = file.path(PATH_HOME, 'Drive', 'HCP900_Parcellation_Timeseries_Netmats_ICAd25')
PATH      = file.path(PATH_HOME, 'workspace', 'MDM-nbooks')
PATH_DATA = file.path(PATH, 'data')

N      = 500
N_comp = 10 # RSNs
N_t    = 1200 # Volumes
N_runs = 4
INFO   = 'NetMats10'
SUBJECTS = as.matrix(read.table(file.path(PATH_TS, 'subjectIDs.txt')))
TR=0.72
labels = read.table(file.path(PATH_DATA, 'Net10Labels.txt'), header = T)
labels = labels[order(labels$NoNetMats25),]
COMP=labels$NoNetMats25

print(labels)
```

## Loading network data
```{r Loading network data}
# subj_r1 = vector(mode = "list", length = N)
# subj_r2 = vector(mode = "list", length = N)
# subj_r3 = vector(mode = "list", length = N)
# subj_r4 = vector(mode = "list", length = N)
# 
# for (s in 1:N) {
#   subj_r1[[s]] = read.subject(PATH_NET, sprintf("%s_Run_%03d", SUBJECTS[s], 1), N_comp)
#   subj_r2[[s]] = read.subject(PATH_NET, sprintf("%s_Run_%03d", SUBJECTS[s], 2), N_comp)
#   subj_r3[[s]] = read.subject(PATH_NET, sprintf("%s_Run_%03d", SUBJECTS[s], 3), N_comp)
#   subj_r4[[s]] = read.subject(PATH_NET, sprintf("%s_Run_%03d", SUBJECTS[s], 4), N_comp)
#   print(sprintf("Subject %03d loaded",s))
# }
# 
# mdm.net10.r1 = mdm.group(subj_r1)
# mdm.net10.r2 = mdm.group(subj_r2)
# mdm.net10.r3 = mdm.group(subj_r3)
# mdm.net10.r4 = mdm.group(subj_r4)
# 
# # save some space
# mdm.net10.r1$models = NULL
# mdm.net10.r2$models = NULL
# mdm.net10.r3$models = NULL
# mdm.net10.r4$models = NULL
# 
# f=file(file.path(PATH_DATA,"net10.RData"))
# save(mdm.net10.r1, mdm.net10.r2, mdm.net10.r3, mdm.net10.r4, file = f, compress = T)
# close(f)
load(file.path(PATH_DATA, "net10.RData"))
```

## Plot: discount factor delta distribution per node
```{r Plot: discount factor delta distribution per node, message=FALSE, warning=TRUE, fig.height=5.2, fig.width=7.5}

d.r1=melt(mdm.net10.r1$df_)
d.r2=melt(mdm.net10.r2$df_)
d.r3=melt(mdm.net10.r3$df_)
d.r4=melt(mdm.net10.r4$df_)


p1 = ggplot(d.r1, aes(x=as.factor(Var2), y=value)) + geom_violin() + geom_boxplot(width=0.2) +
  geom_point(shape=1, color="gray50", size=2, position = position_jitter(width = NULL, height = 0.01)) +
  ggtitle(sprintf("Run 1", N)) + ylab("df") + xlab("node")

p2 = ggplot(d.r2, aes(x=as.factor(Var2), y=value)) + geom_violin() + geom_boxplot(width=0.2) +
  geom_point(shape=1, color="gray50", size=2, position = position_jitter(width = NULL, height = 0.01)) +
  ggtitle(sprintf("Run 2", N)) + ylab("df") + xlab("node")

p3 = ggplot(d.r3, aes(x=as.factor(Var2), y=value)) + geom_violin() + geom_boxplot(width=0.2) +
  geom_point(shape=1, color="gray50", size=2, position = position_jitter(width = NULL, height = 0.01)) +
  ggtitle(sprintf("Run 3", N)) + ylab("df") + xlab("node")

p4 = ggplot(d.r4, aes(x=as.factor(Var2), y=value)) + geom_violin() + geom_boxplot(width=0.2) +
  geom_point(shape=1, color="gray50", size=2, position = position_jitter(width = NULL, height = 0.01)) +
  ggtitle(sprintf("Run 4", N)) + ylab("df") + xlab("node")

plot_grid(p1, p2, p3, p4, ncol = 2, nrow = 2)

```

## Correlation between nodes
```{r Correlation between nodes}
# f = list.files(file.path(PATH_TS, "node_timeseries", "3T_HCP820_MSMAll_d25_ts2"), "*.txt")
# # read data
# ts = array(NA, dim=c(N_t, N_comp, N_runs, N))
# for (s in 1:N) {
#   d = scaleTs(as.matrix(read.table(file.path(PATH_TS, "node_timeseries", "3T_HCP820_MSMAll_d25_ts2", f[s]))))
#   assert(nrow(d) == N_t*N_runs)
#   ts[,,1,s] = d[1:1200,COMP]
#   ts[,,2,s] = d[1201:2400,COMP]
#   ts[,,3,s] = d[2401:3600,COMP]
#   ts[,,4,s] = d[3601:4800,COMP]
# }
# 
# f=file(file.path(PATH,"ts10.RData"))
# save(ts, file = f)
# close(f)
load(file.path(PATH_DATA, "ts10.RData"))
```

## Correlation Plots
```{r Correlation Plots, fig.height=4.7, fig.width=6.5}
LIM=c(-0.65,0.65)

p1 = gplotMat(rmdiag(corTs(ts[,,1,])), title=sprintf("Run 1", N), lim=LIM, nodeLabels = labels$Label, axisTextSize = 8, xAngle = 90,
              colMapLabel=expression("Pearson\'s"~italic(r)), gradient = c("blue", "white", "red")) + xlab("Node") + ylab("Node")
p2 = gplotMat(rmdiag(corTs(ts[,,2,])), title=sprintf("Run 2", N), lim=LIM, nodeLabels = labels$Label, axisTextSize = 8, xAngle = 90,
              colMapLabel=expression("Pearson\'s"~italic(r)), gradient = c("blue", "white", "red")) + xlab("Node") + ylab("Node")
p3 = gplotMat(rmdiag(corTs(ts[,,3,])), title=sprintf("Run 3", N), lim=LIM, nodeLabels = labels$Label, axisTextSize = 8, xAngle = 90,
              colMapLabel=expression("Pearson\'s"~italic(r)), gradient = c("blue", "white", "red")) + xlab("Node") + ylab("Node")
p4 = gplotMat(rmdiag(corTs(ts[,,4,])), title=sprintf("Run 4", N), lim=LIM, nodeLabels = labels$Label, axisTextSize = 8, xAngle = 90,
              colMapLabel=expression("Pearson\'s"~italic(r)), gradient = c("blue", "white", "red")) + xlab("Node") + ylab("Node")

plot_grid(p1, p2, p3, p4, ncol = 2, nrow = 2, rel_widths = c(1, 1))
```

## Plot example timeseries
```{r Plot example timeseries, fig.height=8, fig.width=10}
idx = 1:round(120/TR) # first 2 minutes

# random sampling of subject s and nodes n
nodes = 5 # no. of nodes to plot

d = ts[idx,sample(N_comp,nodes),,sample(N,1)]

p1 = ggplot(melt(d[,1,]), aes(x = Var1, y = value, group=Var2, color=as.factor(Var2))) + 
  geom_line() + theme_minimal() + ggtitle("Run 1")

p2 = ggplot(melt(d[,2,]), aes(x = Var1, y = value, group=Var2, color=as.factor(Var2))) +
  geom_line() + theme_minimal() + ggtitle("Run 2")

p3 = ggplot(melt(d[,3,]), aes(x = Var1, y = value, group=Var2, color=as.factor(Var2))) +
  geom_line() + theme_minimal() + ggtitle("Run 3")

p4 = ggplot(melt(d[,4,]), aes(x = Var1, y = value, group=Var2, color=as.factor(Var2))) + 
  geom_line() + theme_minimal() + ggtitle("Run 4")

plot_grid(p1, p2, p3, p4, ncol = 1, nrow = 4, rel_widths = c(1, 1))
```

## Network consistency across subjects
```{r, Network consistency across subjects, fig.height=10, fig.width=6.2}

stats.r1 = binom.nettest(mdm.net10.r1$am, alter = "greater")
stats.r2 = binom.nettest(mdm.net10.r2$am, alter = "greater")
stats.r3 = binom.nettest(mdm.net10.r3$am, alter = "greater")
stats.r4 = binom.nettest(mdm.net10.r4$am, alter = "greater")

mylim = c(0, 0.68)

p1 = gplotMat(stats.r1$adj, title = "Run 1", nodeLabels=labels$Label,
              axisTextSize=8, xAngle=90, lim = mylim)
p2 = gplotMat(rmna(stats.r1$adj_fdr), title = "binom test & FDR",
              nodeLabels=labels$Label, axisTextSize=8, xAngle=90, lim = mylim)

p3 = gplotMat(stats.r2$adj, title = "Run 2", nodeLabels=labels$Label,
              axisTextSize=8, xAngle=90, lim = mylim)
p4 = gplotMat(rmna(stats.r2$adj_fdr), title = "binom test & FDR",
              nodeLabels=labels$Label, axisTextSize=8, xAngle=90, lim = mylim)

p5 = gplotMat(stats.r3$adj, title = "Run 3", nodeLabels=labels$Label,
              axisTextSize=8, xAngle=90, lim = mylim)
p6 = gplotMat(rmna(stats.r3$adj_fdr), title = "binom test & FDR",
              nodeLabels=labels$Label, axisTextSize=8, xAngle=90, lim = mylim)

p7 = gplotMat(stats.r4$adj, title = "Run 4", nodeLabels=labels$Label,
              axisTextSize=8, xAngle=90, lim = mylim)
p8 = gplotMat(rmna(stats.r4$adj_fdr), title = "binom test & FDR",
              nodeLabels=labels$Label, axisTextSize=8, xAngle=90, lim = mylim)

plot_grid(p1, p2, p3, p4, p5, p6, p7, p8, ncol = 2, nrow = 4, rel_heights = c(1,1,1,1))
```

## Networks consistency across runs
```{r Networks consistency across runs, fig.height=7.5, fig.width=6.2}
# edge reproduced in 3 runs or more
m3 = mdm.net10.r1$am + mdm.net10.r2$am + mdm.net10.r3$am + mdm.net10.r4$am > 2
# edge reproduced in all runs
m4 = mdm.net10.r1$am * mdm.net10.r2$am * mdm.net10.r3$am * mdm.net10.r4$am
# consistently no edge in all runs
mn = (1-mdm.net10.r1$am) * (1-mdm.net10.r2$am) * (1-mdm.net10.r3$am) * (1-mdm.net10.r4$am)


stats.m3 = binom.nettest(m3, alter = "greater")
stats.m4 = binom.nettest(m4, alter = "greater")
stats.mn = binom.nettest(mn, alter = "greater")

p1 = gplotMat(stats.m3$adj, title = "edge in 3/4 runs", nodeLabels=labels$Label,
              axisTextSize=8, xAngle=90, lim = c(0, 0.6))
p2 = gplotMat(rmna(stats.m3$adj_fdr), title = "binom test & FDR",
              nodeLabels=labels$Label, axisTextSize=8, xAngle=90, lim = c(0, 0.6))

p3 = gplotMat(stats.m4$adj, title = "edge in 4/4 runs", nodeLabels=labels$Label,
              axisTextSize=8, xAngle=90, lim = c(0, 0.32))
p4 = gplotMat(rmna(stats.m4$adj_fdr), title = "binom test & FDR",
              nodeLabels=labels$Label, axisTextSize=8, xAngle=90, lim = c(0,0.32))

p5 = gplotMat(rmdiag(stats.mn$adj), title = "no edge in 4/4 runs", nodeLabels=labels$Label,
              gradient = c("white", "violet", "blue"),
              axisTextSize=8, xAngle=90)
p6 = gplotMat(rmdiag(rmna(stats.mn$adj_fdr)), title = "binom test & FDR",
              gradient = c("white", "violet", "blue"),
              nodeLabels=labels$Label, axisTextSize=8, xAngle=90)

plot_grid(p1, p2, p3, p4, p5, p6, labels=c("A", "", "", "", "B", ""),
          ncol = 2, nrow = 3, rel_heights = c(1,1,1))
```

