---
title: "MDM-Mouse"
author: "Simon Schwab"
date: "6 April 2017"
output: html_document
---

### Install R Markdown 
```{r Install R Markdown}
# install.packages("rmarkdown")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Install required packages 
```{r install required packages}
# install.packages("devtools")
# install.packages("testit")
# install.packages("ggplot2")
# install.packages("cowplot")
# install.packages("reshape2")
```

### Load libraries 
```{r Load required libraries, message=FALSE}
library(devtools)
library(testit)
library(ggplot2)
library(cowplot)
library(reshape2)
```

### Install and load multdyn 
```{r Install multdyn, message=FALSE}
# install_github("schw4b/multdyn", ref = "develop")
# library(multdyn)

# I'm using my local development branch
load_all('~/workspace/multdyn')
```

### Main variables 
```{r Main variables}
N=16 # Number of simulated subjects/datasets
Nn=14 # Number of nodes, does not apply to all datasets
Nn1=8
Nn2=6
N_t= 2000 # Volumes/no. of timepoints
PATH_HOME = "/home/simon"
PATH = file.path(PATH_HOME, 'workspace', 'MDM-nbooks') # path where figures will be stored
PATH_DATA = file.path(PATH_HOME, "Drive", "Mouse")
```

### Loading network data
```{r Loading network data}
# subj=list()
# for (s in 1:N) {
#   subj[[s]] = read.subject(file.path(PATH_DATA, 'Mouse_14ROIs_CP_results'), sprintf("Mouse_%03d",s), 14)
# }
# mdm.mouse14=mdm.group(subj)
# 
# subj=list()
# for (s in 1:8) {
#   subj[[s]] = read.subject(file.path(PATH_DATA, 'Mouse_N816ROIs_results'), sprintf("Mouse_%03d",s), 16)
# }
# mdm.mouse16=mdm.group(subj)
# 
# subj=list()
# for (s in 1:N) {
#   subj[[s]] = read.subject(file.path(PATH_DATA, 'Net1_WT_results'), sprintf("Mouse_%03d",s), 8)
# }
# mdm.net1wt=mdm.group(subj)
# 
# subj=list()
# for (s in 1:N) {
#   subj[[s]] = read.subject(file.path(PATH_DATA, 'Net2_WT_results'), sprintf("Mouse_%03d",s), 6)
# }
# mdm.net2wt=mdm.group(subj)

# takes quite long to load above data
#setwd(PATH)
#save(mdm.mouse14, mdm.mouse16, mdm.net1wt, mdm.net2wt, file = "mdm-mouse.RData")

load(file.path(PATH,"mdm-mouse.RData"))

```

### Plot: discount factor delta distribution per node
```{r Plot: discount factor delta distribution per node, message=FALSE, warning=TRUE, fig.height=5.2, fig.width=6.5}

node=as.factor(sort(rep(1:14,N)))
d1=data.frame(df=c(mdm.mouse14$df_), node=node)

node=as.factor(sort(rep(1:16,8)))
d2=data.frame(df=c(mdm.mouse16$df_), node=node)

node=as.factor(sort(rep(1:8,N)))
d3=data.frame(df=c(mdm.net1wt$df_),  node=node)

node=as.factor(sort(rep(1:6,16)))
d4=data.frame(df=c(mdm.net2wt$df_),  node=node)

p1 = ggplot(d1, aes(x=node, y=df)) + geom_violin() + geom_boxplot(width=0.2) +
  geom_point(shape=1, color="gray50", size=2, position = position_jitter(width = 0.2, height = 0.0002)) + ggtitle("Mouse 14 ROIs (N=16)")
p2 = ggplot(d2, aes(x=node, y=df)) + geom_violin() + geom_boxplot(width=0.2) +
  geom_point(shape=1, color="gray50", size=2, position = position_jitter(width = 0.2, height = 0.0002)) + ggtitle("Mouse 16 ROIs (N=8)")
p3 = ggplot(d3, aes(x=node, y=df)) + geom_violin() + geom_boxplot(width=0.2) +
  geom_point(shape=1, color="gray50", size=2, position = position_jitter(width = 0.2, height = 0.0002)) + ggtitle("Net1_WT (N=16)")
p4 = ggplot(d4, aes(x=node, y=df)) + geom_violin() + geom_boxplot(width=0.2) +
  geom_point(shape=1, color="gray50", size=2, position = position_jitter(width = 0.2, height = 0.0002)) + ggtitle("Net2_WT (N=16)")

plot_grid(p1, p2, p3, p4, ncol = 2, nrow = 2)
```

### Correlation plot
```{r Correlation plot, fig.height=4, fig.width=5.8}
f14 = list.files(file.path(PATH_DATA, "Timeseries_14ROIs_CP"), "*.txt")
f16 = list.files(file.path(PATH_DATA, "WT_fmr1ko_120d_dr_stage1"), "*.txt")
f1  = list.files(file.path(PATH_DATA, "Net1_WT"), "*.txt")
f2  = list.files(file.path(PATH_DATA, "Net2_WT"), "*.txt")
assert(length(f14) == N)
assert(length(f16) == 8)
assert(length(f1)  == N)
assert(length(f2)  == N)

# read data
d14 = array(NA, dim=c(N_t, Nn, N))
d16 = array(NA, dim=c(N_t, 16, 8))
d1  = array(NA, dim=c(N_t, Nn1, N))
d2  = array(NA, dim=c(N_t, Nn2, N))
for (s in 1:N) {
  d14[,,s]= scaleTs(as.matrix(read.table(file.path(PATH_DATA, "Timeseries_14ROIs_CP", f14[s]))))
  if (s <=8) {
    d16[,,s]= scaleTs(as.matrix(read.table(file.path(PATH_DATA, "WT_fmr1ko_120d_dr_stage1", f16[s]))))
  }
  d1[,,s] = scaleTs(as.matrix(read.table(file.path(PATH_DATA, "Net1_WT", f1[s]))))
  d2[,,s] = scaleTs(as.matrix(read.table(file.path(PATH_DATA, "Net2_WT", f2[s]))))
  #d=scaleTs(d)
  assert(nrow(d14) == N_t)
  assert(nrow(d16) == N_t)
  assert(nrow(d1) == N_t)
  assert(nrow(d2) == N_t)
  assert(ncol(d14) == Nn)
  assert(ncol(d16) == 16)
  assert(ncol(d1) == Nn1)
  assert(ncol(d2) == Nn2)
}

p1 = gplotMat(rmdiag(corTs(d14)), title='14 ROIs (N=16)', lim=c(0, 1),
              label=expression("Pearson\'s"~italic(r))) + xlab("Node") + ylab("Node")
p2 = gplotMat(rmdiag(corTs(d16)), title='16 ROIs (N=8)', lim=c(-0.4, 0.6),
              label=expression("Pearson\'s"~italic(r)), gradient = c("blue", "white", "red")) + xlab("Node") + ylab("Node")
p3 = gplotMat(rmdiag(corTs(d1)), title='Net1_WT (N=16)', lim=c(0, 0.5),
              label=expression("Pearson\'s"~italic(r))) + xlab("Node") + ylab("Node")
p4 = gplotMat(rmdiag(corTs(d2)), title='Net2_WT (N=16)', lim=c(0, 0.5),
              label=expression("Pearson\'s"~italic(r))) + xlab("Node") + ylab("Node")

plot_grid(p1, p2, p3, p4, ncol = 2, nrow = 2, rel_widths = c(1, 1))

```

### Plot random timeseries
```{r Plot random timeseries, fig.height=8, fig.width=10}
t = 1:200 # interval to plot

# random sampling mice m and nodes n
nodes = 5 # no. of nodes to plot

d = melt(d14[t,sample(14,nodes),sample(N,1)])
p1=ggplot(d, aes(x = Var1, y = value, group=Var2, color=as.factor(Var2))) + geom_line() + theme_minimal() + 
  ggtitle("Mouse 14 ROIs")

d = melt(d16[t,sample(16,nodes),sample(8,1)])
p2=ggplot(d, aes(x = Var1, y = value, group=Var2, color=as.factor(Var2))) + geom_line() + theme_minimal() + ggtitle("Mouse 16 ROIs")

d = melt(d1[t,sample(8,nodes),sample(N,1)])
p3=ggplot(d, aes(x = Var1, y = value, group=Var2, color=as.factor(Var2))) + geom_line() + theme_minimal() + ggtitle("Net1_WT")

d = melt(d2[t,sample(6,nodes),sample(N,1)])
p4=ggplot(d, aes(x = Var1, y = value, group=Var2, color=as.factor(Var2))) + geom_line() + theme_minimal() + ggtitle("Net2_WT")

plot_grid(p1, p2, p3, p4, ncol = 1, nrow = 4, rel_widths = c(1, 1))

```

### Network consistency across mice

```{r, Network consistency across mice, fig.height=8, fig.width=5.2}

stats1 = binom.nettest(mdm.mouse14$am)
stats2 = binom.nettest(mdm.mouse16$am)
stats3 = binom.nettest(mdm.net1wt$am)
stats4 = binom.nettest(mdm.net2wt$am)

p1 = gplotMat(stats1$adj) + ggtitle("Mouse 14 ROIs")
p2 = gplotMat(rmna(stats1$adj_fdr)) + ggtitle("binom test & FDR")

p3 = gplotMat(stats2$adj) + ggtitle("Mouse 16 ROIs")
p4 = gplotMat(rmna(stats2$adj_fdr)) + ggtitle("binom test & FDR")

p5 = gplotMat(stats3$adj) + ggtitle("Net1_WT")
p6 = gplotMat(rmna(stats3$adj_fdr)) + ggtitle("binom test & FDR")

p7 = gplotMat(stats4$adj) + ggtitle("Net2_WT")
p8 = gplotMat(rmna(stats4$adj_fdr))  + ggtitle("binom test & FDR")


plot_grid(p1, p2, p3, p4, p5, p6, p7, p8, ncol = 2, nrow = 4)

```




